import type { Vehicle } from '@/types/vehicle'

export const vehicles: Vehicle[] = [
  // ─── CIVILIAN ───────────────────────────────────────────────────
  {
    slug: 'armoured-land-cruiser-300',
    name: 'Armoured Land Cruiser 300',
    category: 'civilian',
    platform: 'Toyota Land Cruiser 300 GXR',
    protectionLevel: 'BR7',
    status: 'available',
    heroImage: '/images/vehicles/lc300-hero.jpg',
    galleryImages: [
      '/images/vehicles/lc300-01.jpg',
      '/images/vehicles/lc300-02.jpg',
      '/images/vehicles/lc300-03.jpg',
      '/images/vehicles/lc300-04.jpg',
    ],
    specs: {
      'Base Platform': 'Toyota Land Cruiser 300 GXR',
      'Armour Type': 'High-hardness ballistic steel + polycarbonate composite',
      'Protection Standard': 'EN 1063 BR7 / VPAM VR7',
      'Engine': '3.5L Twin-Turbo V6 / 305 hp',
      'Transmission': '10-speed automatic',
      'Gross Vehicle Weight': '5,200 kg',
      'Seating Capacity': '5+1',
      'Run-Flat System': 'Hutchinson run-flat inserts',
      'Blast Protection': 'ERB Level 2',
      'Fuel Tank': 'Armoured, self-sealing',
    },
    highlights: ['Invisible armouring', 'Run-flat capable', 'BR7 certified'],
    description:
      'The Armoured Land Cruiser 300 is our flagship civilian protection platform. Built on Toyota\'s most capable SUV, the armour package is engineered to be indistinguishable from the factory original while delivering EN 1063 BR7 protection. Specified for heads of state, senior executives, and high-value personnel operating in elevated-threat environments.',
    optionalUpgrades: [
      'Siren & PA System',
      'Emergency Lighting',
      'Intercom System',
      'Night Vision Camera',
      'Smoke Dispensers',
      'Medical Kit',
      'GPS Tracker',
      'Tinted OEM Glass',
      'Satellite Comms',
    ],
    weight: '5,200 kg',
    seats: 6,
  },
  {
    slug: 'armoured-prado',
    name: 'Armoured Prado',
    category: 'civilian',
    platform: 'Toyota Land Cruiser Prado',
    protectionLevel: 'BR6',
    status: 'available',
    heroImage: '/images/vehicles/prado-hero.jpg',
    galleryImages: [
      '/images/vehicles/prado-01.jpg',
      '/images/vehicles/prado-02.jpg',
      '/images/vehicles/prado-03.jpg',
      '/images/vehicles/prado-04.jpg',
    ],
    specs: {
      'Base Platform': 'Toyota Land Cruiser Prado 4.0L',
      'Armour Type': 'Ballistic steel + laminated glass',
      'Protection Standard': 'EN 1063 BR6',
      'Engine': '4.0L V6 / 270 hp',
      'Transmission': '6-speed automatic',
      'Gross Vehicle Weight': '4,100 kg',
      'Seating Capacity': '7',
      'Run-Flat System': 'Available',
      'Blast Protection': 'ERB Level 1',
      'Fuel Tank': 'Armoured',
    },
    highlights: ['7-seat capacity', 'Discreet profile', 'BR6 certified'],
    description:
      'A versatile mid-size protection platform suited to corporate security teams and family protection details. The Armoured Prado delivers BR6 ballistic resistance with full seven-seat retention — a rare combination. Widely deployed across West Africa and the Gulf.',
    optionalUpgrades: [
      'Siren & PA System',
      'Emergency Lighting',
      'GPS Tracker',
      'Medical Kit',
      'Tinted OEM Glass',
    ],
    weight: '4,100 kg',
    seats: 7,
  },
  {
    slug: 'armoured-mercedes-g-class',
    name: 'Armoured Mercedes G-Class',
    category: 'civilian',
    platform: 'Mercedes-Benz G 63 AMG',
    protectionLevel: 'BR7',
    status: 'made-to-order',
    heroImage: '/images/vehicles/gclass-hero.jpg',
    galleryImages: [
      '/images/vehicles/gclass-01.jpg',
      '/images/vehicles/gclass-02.jpg',
      '/images/vehicles/gclass-03.jpg',
      '/images/vehicles/gclass-04.jpg',
    ],
    specs: {
      'Base Platform': 'Mercedes-Benz G 63 AMG',
      'Armour Type': 'Ultra-high-hardness steel + multi-layer glass',
      'Protection Standard': 'EN 1063 BR7 / VPAM VR7',
      'Engine': '4.0L V8 Biturbo / 577 hp',
      'Transmission': '9-speed automatic',
      'Gross Vehicle Weight': '4,800 kg',
      'Seating Capacity': '4+1',
      'Run-Flat System': 'Standard',
      'Blast Protection': 'ERB Level 2',
      'Fuel Tank': 'Armoured, self-sealing',
    },
    highlights: ['Maximum BR7 protection', '577 hp performance', 'Iconic profile'],
    description:
      'The Armoured G 63 AMG combines the iconic presence of the Mercedes G-Class with maximum BR7 ballistic protection. Made to order, each build is configured to the client\'s specification. Performance is uncompromised — 577 hp ensures immediate mobility under any threat condition.',
    optionalUpgrades: [
      'Emergency Lighting',
      'Night Vision Camera',
      'GPS Tracker',
      'Satellite Comms',
      'Smoke Dispensers',
    ],
    weight: '4,800 kg',
    seats: 5,
  },
  {
    slug: 'armoured-toyota-hilux',
    name: 'Armoured Toyota Hilux Pickup',
    category: 'civilian',
    platform: 'Toyota Hilux Revo',
    protectionLevel: 'BR6',
    status: 'available',
    heroImage: '/images/vehicles/hilux-hero.jpg',
    galleryImages: [
      '/images/vehicles/hilux-01.jpg',
      '/images/vehicles/hilux-02.jpg',
      '/images/vehicles/hilux-03.jpg',
      '/images/vehicles/hilux-04.jpg',
    ],
    specs: {
      'Base Platform': 'Toyota Hilux Revo Double Cab',
      'Armour Type': 'Ballistic steel + polycarbonate glass',
      'Protection Standard': 'EN 1063 BR6',
      'Engine': '2.8L Turbodiesel / 204 hp',
      'Transmission': '6-speed automatic',
      'Gross Vehicle Weight': '3,400 kg',
      'Seating Capacity': '4',
      'Run-Flat System': 'Optional',
      'Blast Protection': 'ERB Level 1',
      'Fuel Tank': 'Armoured',
    },
    highlights: ['All-terrain capable', 'Low-profile protection', 'BR6 certified'],
    description:
      'The most operationally flexible platform in our civilian range. The Armoured Hilux is used extensively by oil and gas field teams, NGO security advisors, and rural executive protection details. Reliable in terrain that would compromise larger vehicles.',
    optionalUpgrades: ['GPS Tracker', 'Medical Kit', 'Intercom System', 'Emergency Lighting'],
    weight: '3,400 kg',
    seats: 4,
  },
  {
    slug: 'armoured-toyota-coaster',
    name: 'Armoured Toyota Coaster Bus',
    category: 'civilian',
    platform: 'Toyota Coaster',
    protectionLevel: 'BR6',
    status: 'made-to-order',
    heroImage: '/images/vehicles/coaster-hero.jpg',
    galleryImages: [
      '/images/vehicles/coaster-01.jpg',
      '/images/vehicles/coaster-02.jpg',
      '/images/vehicles/coaster-03.jpg',
      '/images/vehicles/coaster-04.jpg',
    ],
    specs: {
      'Base Platform': 'Toyota Coaster 30-seat',
      'Armour Type': 'Ballistic steel panels + laminated glass',
      'Protection Standard': 'EN 1063 BR6',
      'Engine': '4.2L Turbodiesel / 195 hp',
      'Transmission': '5-speed manual',
      'Gross Vehicle Weight': '7,800 kg',
      'Seating Capacity': 'Up to 22 (configured)',
      'Run-Flat System': 'Standard',
      'Blast Protection': 'ERB Level 1',
      'Fuel Tank': 'Armoured',
    },
    highlights: ['22-person capacity', 'VIP or standard configuration', 'BR6 certified'],
    description:
      'The Armoured Coaster is engineered for diplomatic convoys, senior delegation movements, and high-profile group transfers. Available in VIP configuration with reduced seating and premium interior, or standard layout for escort and security team transport.',
    optionalUpgrades: ['Siren & PA System', 'Emergency Lighting', 'Intercom System', 'GPS Tracker'],
    weight: '7,800 kg',
    seats: 22,
  },
  {
    slug: 'armoured-mercedes-sprinter',
    name: 'Armoured Mercedes Sprinter',
    category: 'civilian',
    platform: 'Mercedes-Benz Sprinter 316',
    protectionLevel: 'BR4',
    status: 'available',
    heroImage: '/images/vehicles/sprinter-hero.jpg',
    galleryImages: [
      '/images/vehicles/sprinter-01.jpg',
      '/images/vehicles/sprinter-02.jpg',
      '/images/vehicles/sprinter-03.jpg',
      '/images/vehicles/sprinter-04.jpg',
    ],
    specs: {
      'Base Platform': 'Mercedes-Benz Sprinter 316 CDI',
      'Armour Type': 'Lightweight ballistic composite',
      'Protection Standard': 'EN 1063 BR4',
      'Engine': '2.1L Turbodiesel / 163 hp',
      'Transmission': '7-speed automatic',
      'Gross Vehicle Weight': '5,100 kg',
      'Seating Capacity': '8–12 (configured)',
      'Run-Flat System': 'Optional',
      'Blast Protection': 'Not standard',
      'Fuel Tank': 'Standard',
    },
    highlights: ['Cash transport ready', 'Lightweight composite armour', 'BR4 certified'],
    description:
      'The Armoured Sprinter serves cash-in-transit operators, pharmaceutical logistics companies, and secure document transport fleets. BR4 protection delivers effective coverage against small-arms fire at a lower weight penalty, preserving payload capacity.',
    optionalUpgrades: ['GPS Tracker', 'Intercom System', 'Emergency Lighting'],
    weight: '5,100 kg',
    seats: 10,
  },
  {
    slug: 'armoured-mercedes-s-class',
    name: 'Armoured Mercedes S-Class',
    category: 'civilian',
    platform: 'Mercedes-Benz S 580 L',
    protectionLevel: 'BR7',
    status: 'made-to-order',
    heroImage: '/images/vehicles/sclass-hero.jpg',
    galleryImages: [
      '/images/vehicles/sclass-01.jpg',
      '/images/vehicles/sclass-02.jpg',
      '/images/vehicles/sclass-03.jpg',
      '/images/vehicles/sclass-04.jpg',
    ],
    specs: {
      'Base Platform': 'Mercedes-Benz S 580 L 4MATIC',
      'Armour Type': 'Ultra-high-hardness steel + OptiWhite glass',
      'Protection Standard': 'EN 1063 BR7 / VPAM VR7',
      'Engine': '4.0L V8 Biturbo / 503 hp',
      'Transmission': '9-speed automatic',
      'Gross Vehicle Weight': '4,600 kg',
      'Seating Capacity': '4',
      'Run-Flat System': 'Standard',
      'Blast Protection': 'ERB Level 2',
      'Fuel Tank': 'Armoured, self-sealing',
    },
    highlights: ['Civilian flagship', 'Completely invisible protection', 'BR7 certified'],
    description:
      'Our most refined civilian platform. The Armoured S-Class is specified for heads of state, sitting ministers, and corporate principals who require maximum protection without any visible departure from the factory vehicle. Every integration is executed to Mercedes-Benz tolerances.',
    optionalUpgrades: [
      'Night Vision Camera',
      'Satellite Comms',
      'Intercom System',
      'GPS Tracker',
    ],
    weight: '4,600 kg',
    seats: 4,
  },
  {
    slug: 'armoured-range-rover-defender',
    name: 'Armoured Range Rover Defender',
    category: 'civilian',
    platform: 'Land Rover Defender 110',
    protectionLevel: 'BR6',
    status: 'available',
    heroImage: '/images/vehicles/defender-hero.jpg',
    galleryImages: [
      '/images/vehicles/defender-01.jpg',
      '/images/vehicles/defender-02.jpg',
      '/images/vehicles/defender-03.jpg',
      '/images/vehicles/defender-04.jpg',
    ],
    specs: {
      'Base Platform': 'Land Rover Defender 110',
      'Armour Type': 'Ballistic steel + polycarbonate composite',
      'Protection Standard': 'EN 1063 BR6',
      'Engine': '3.0L Turbodiesel / 300 hp',
      'Transmission': '8-speed automatic',
      'Gross Vehicle Weight': '4,300 kg',
      'Seating Capacity': '5',
      'Run-Flat System': 'Standard',
      'Blast Protection': 'ERB Level 1',
      'Fuel Tank': 'Armoured',
    },
    highlights: ['Off-road capable', 'Terrain response system retained', 'BR6 certified'],
    description:
      'The Armoured Defender retains Land Rover\'s full Terrain Response system and off-road geometry within the armoured configuration. Operated by NGO field teams, mining sector security, and private expedition security worldwide.',
    optionalUpgrades: ['GPS Tracker', 'Medical Kit', 'Emergency Lighting', 'Intercom System'],
    weight: '4,300 kg',
    seats: 5,
  },

  // ─── MILITARY ───────────────────────────────────────────────────
  {
    slug: 'armoured-personnel-carrier',
    name: 'Armoured Personnel Carrier',
    category: 'military',
    platform: 'Purpose-built / client platform',
    protectionLevel: 'STANAG L2',
    status: 'made-to-order',
    heroImage: '/images/vehicles/apc-hero.jpg',
    galleryImages: [
      '/images/vehicles/apc-01.jpg',
      '/images/vehicles/apc-02.jpg',
      '/images/vehicles/apc-03.jpg',
      '/images/vehicles/apc-04.jpg',
    ],
    specs: {
      'Platform Type': 'Wheeled APC — 4×4 or 6×6',
      'Armour Type': 'High-hardness rolled steel with spall liner',
      'Protection Standard': 'STANAG 4569 Level 2',
      'Engine': 'Cummins 6BT / 190 hp',
      'Transmission': '6-speed manual / automatic available',
      'Gross Vehicle Weight': '12,500 kg',
      'Troop Capacity': '10 + 2 crew',
      'Run-Flat System': 'Standard all axles',
      'Blast Protection': 'STANAG L2 mine blast',
      'Armament Mount': 'Optional ring mount',
    },
    highlights: ['STANAG L2 certified', '10-troop capacity', 'Mine blast protection'],
    description:
      'A proven wheeled APC configured to STANAG 4569 Level 2. Available as a purpose-built platform or integrated onto a client-supplied chassis. Specified by national defence forces across West Africa for infantry transport, perimeter security, and convoy escort duties.',
    optionalUpgrades: [
      'Ring Mount / Pintle',
      'Night Vision System',
      'Smoke Dispensers',
      'NBC Filter',
      'Satellite Comms',
      'GPS Tracker',
      'Intercom System',
    ],
    weight: '12,500 kg',
    seats: 12,
  },
  {
    slug: 'mine-resistant-ambush-protected',
    name: 'Mine Resistant Ambush Protected',
    category: 'military',
    platform: 'Purpose-built MRAP',
    protectionLevel: 'STANAG L3',
    status: 'made-to-order',
    heroImage: '/images/vehicles/mrap-hero.jpg',
    galleryImages: [
      '/images/vehicles/mrap-01.jpg',
      '/images/vehicles/mrap-02.jpg',
      '/images/vehicles/mrap-03.jpg',
      '/images/vehicles/mrap-04.jpg',
    ],
    specs: {
      'Platform Type': 'MRAP — 4×4',
      'Armour Type': 'V-hull blast deflector + armour steel',
      'Protection Standard': 'STANAG 4569 Level 3',
      'Engine': 'Cummins ISB / 285 hp',
      'Transmission': 'Allison 3500 automatic',
      'Gross Vehicle Weight': '18,000 kg',
      'Troop Capacity': '6 + 2 crew',
      'Run-Flat System': 'Central Tyre Inflation standard',
      'Blast Protection': 'STANAG L3 mine blast / IED',
      'Armament Mount': 'Remote Weapon Station compatible',
    },
    highlights: ['STANAG L3 blast protection', 'V-hull design', 'IED resistant'],
    description:
      'Our MRAP platform delivers STANAG 4569 Level 3 protection — the highest mine and IED blast resistance available in the wheeled category. The V-hull geometry is proven to deflect underbody blast energy away from the crew compartment. Deployed in active theatre environments.',
    optionalUpgrades: [
      'Remote Weapon Station',
      'Smoke Dispensers',
      'NBC Filter',
      'Night Vision System',
      'Satellite Comms',
      'Medical Kit',
    ],
    weight: '18,000 kg',
    seats: 8,
  },
  {
    slug: 'infantry-fighting-vehicle',
    name: 'Infantry Fighting Vehicle',
    category: 'military',
    platform: 'Purpose-built IFV',
    protectionLevel: 'STANAG L3',
    status: 'made-to-order',
    heroImage: '/images/vehicles/ifv-hero.jpg',
    galleryImages: [
      '/images/vehicles/ifv-01.jpg',
      '/images/vehicles/ifv-02.jpg',
      '/images/vehicles/ifv-03.jpg',
      '/images/vehicles/ifv-04.jpg',
    ],
    specs: {
      'Platform Type': 'Tracked IFV',
      'Armour Type': 'Modular appliqué steel + composite',
      'Protection Standard': 'STANAG 4569 Level 3',
      'Engine': 'Diesel / 400 hp',
      'Transmission': 'Hydrostatic drive',
      'Combat Weight': '22,000 kg',
      'Troop Capacity': '6 + 3 crew',
      'Armament': '23mm autocannon + co-axial 7.62mm',
      'Blast Protection': 'STANAG L3',
      'Amphibious': 'Optional',
    },
    highlights: ['23mm main armament', 'Tracked mobility', 'STANAG L3 certified'],
    description:
      'The IFV combines maximum firepower with STANAG Level 3 ballistic and blast protection. Available with a 23mm autocannon or client-specified armament in a fully integrated turret. Suited to national armed forces conducting combined arms operations.',
    optionalUpgrades: [
      'Remote Weapon Station',
      'Reactive Armour Tiles',
      'Night Vision System',
      'Smoke Dispensers',
      'NBC Filter',
      'Amphibious Kit',
    ],
    weight: '22,000 kg',
    seats: 9,
  },
  {
    slug: 'riot-control-vehicle',
    name: 'Riot Control Vehicle',
    category: 'military',
    platform: 'Mercedes-Benz Actros / MAN',
    protectionLevel: 'BR6',
    status: 'made-to-order',
    heroImage: '/images/vehicles/rcv-hero.jpg',
    galleryImages: [
      '/images/vehicles/rcv-01.jpg',
      '/images/vehicles/rcv-02.jpg',
      '/images/vehicles/rcv-03.jpg',
      '/images/vehicles/rcv-04.jpg',
    ],
    specs: {
      'Base Platform': 'Mercedes-Benz Actros 8×4',
      'Armour Type': 'Ballistic steel cab + reinforced chassis',
      'Protection Standard': 'EN 1063 BR6',
      'Engine': '12.8L Turbodiesel / 390 hp',
      'Water Cannon': '10,000L capacity / 60m range',
      'Chemical Dispersal': 'Optional dye marker system',
      'Crew': '3',
      'Observation System': '360° CCTV',
      'Blast Protection': 'ERB Level 1',
      'PA System': 'Standard',
    },
    highlights: ['10,000L water cannon', '60m effective range', 'BR6 cab protection'],
    description:
      'Engineered for police and paramilitary public order operations. The RCV delivers 10,000 litres of water or chemical dispersal agent at range, with a fully armoured cab protecting the three-person crew from BR6-class projectiles.',
    optionalUpgrades: ['Dye Marker System', 'Night Vision', 'Foam Dispersal', 'Additional Cameras'],
    weight: '26,000 kg',
    seats: 3,
  },
  {
    slug: 'armoured-ambulance',
    name: 'Armoured Ambulance',
    category: 'military',
    platform: 'Toyota Land Cruiser 79 Series',
    protectionLevel: 'BR6',
    status: 'available',
    heroImage: '/images/vehicles/ambulance-hero.jpg',
    galleryImages: [
      '/images/vehicles/ambulance-01.jpg',
      '/images/vehicles/ambulance-02.jpg',
      '/images/vehicles/ambulance-03.jpg',
      '/images/vehicles/ambulance-04.jpg',
    ],
    specs: {
      'Base Platform': 'Toyota Land Cruiser 79 Series',
      'Armour Type': 'Ballistic steel + laminated glass',
      'Protection Standard': 'EN 1063 BR6',
      'Engine': '4.5L V8 Turbodiesel / 195 hp',
      'Transmission': '5-speed manual',
      'Gross Vehicle Weight': '4,500 kg',
      'Medical Capacity': '1 stretcher + 2 seated patients',
      'Medical Equipment': 'Full trauma fit-out',
      'Run-Flat System': 'Standard',
      'Comms': 'Military radio integrated',
    },
    highlights: ['Full trauma fit-out', 'BR6 protection', 'Forward operating capable'],
    description:
      'The Armoured Ambulance enables medical teams to operate at the point of wounding in hostile environments. Built on the Toyota 79 Series for reliability in austere terrain, it carries a full trauma fit-out while maintaining BR6 ballistic protection throughout.',
    optionalUpgrades: ['Advanced Trauma Kit', 'Satellite Comms', 'Generator', 'Refrigeration'],
    weight: '4,500 kg',
    seats: 5,
  },
  {
    slug: 'cash-in-transit-vehicle',
    name: 'Cash-in-Transit Vehicle',
    category: 'military',
    platform: 'Toyota Land Cruiser 79 Series',
    protectionLevel: 'BR7',
    status: 'available',
    heroImage: '/images/vehicles/cit-hero.jpg',
    galleryImages: [
      '/images/vehicles/cit-01.jpg',
      '/images/vehicles/cit-02.jpg',
      '/images/vehicles/cit-03.jpg',
      '/images/vehicles/cit-04.jpg',
    ],
    specs: {
      'Base Platform': 'Toyota Land Cruiser 79 Series',
      'Armour Type': 'Ultra-high-hardness steel + BR7 glass',
      'Protection Standard': 'EN 1063 BR7',
      'Engine': '4.5L V8 Turbodiesel / 195 hp',
      'Transmission': '5-speed manual',
      'Vault': 'Welded steel secure compartment',
      'Crew': '2',
      'Run-Flat System': 'Standard',
      'Lock System': 'Dual-key electronic / manual override',
      'Blast Protection': 'ERB Level 1',
    },
    highlights: ['BR7 maximum protection', 'Welded secure vault', 'Dual-key locking'],
    description:
      'The CIT vehicle is built to the same ballistic standard as head-of-state transport. The rear vault compartment is welded structural steel with electronic and manual locking. Operated by central banks, commercial banks, and high-value logistics operators throughout Sub-Saharan Africa.',
    optionalUpgrades: ['GPS Tracker', 'Emergency Lighting', 'Siren & PA System', 'Dye Pack System'],
    weight: '3,800 kg',
    seats: 2,
  },
  {
    slug: 'light-tactical-vehicle',
    name: 'Light Tactical Vehicle',
    category: 'military',
    platform: 'Toyota Hilux / Ford Ranger',
    protectionLevel: 'STANAG L1',
    status: 'available',
    heroImage: '/images/vehicles/ltv-hero.jpg',
    galleryImages: [
      '/images/vehicles/ltv-01.jpg',
      '/images/vehicles/ltv-02.jpg',
      '/images/vehicles/ltv-03.jpg',
      '/images/vehicles/ltv-04.jpg',
    ],
    specs: {
      'Base Platform': 'Toyota Hilux Revo / Ford Ranger Raptor',
      'Armour Type': 'Lightweight ballistic steel + polycarbonate',
      'Protection Standard': 'STANAG 4569 Level 1',
      'Engine': '2.8L Turbodiesel / 204 hp',
      'Transmission': '6-speed automatic',
      'Gross Vehicle Weight': '3,200 kg',
      'Crew': '2 + 2 in open bed',
      'Armament Mount': 'Rear roll bar pintle mount',
      'Run-Flat System': 'Optional',
      'Blast Protection': 'Level 1',
    },
    highlights: ['Rapid deployment', 'Pintle mount compatible', 'STANAG L1 certified'],
    description:
      'The LTV provides STANAG Level 1 protection in a compact, high-mobility format. Widely used by border security forces, quick-reaction teams, and special operations units requiring protected mobility without the logistics burden of heavier platforms.',
    optionalUpgrades: ['Pintle Mount', 'Night Vision', 'GPS Tracker', 'Roll Cage', 'Winch'],
    weight: '3,200 kg',
    seats: 4,
  },
  {
    slug: 'mobile-command-vehicle',
    name: 'Mobile Command Vehicle',
    category: 'military',
    platform: 'Mercedes-Benz Sprinter / Toyota Coaster',
    protectionLevel: 'BR6',
    status: 'made-to-order',
    heroImage: '/images/vehicles/command-hero.jpg',
    galleryImages: [
      '/images/vehicles/command-01.jpg',
      '/images/vehicles/command-02.jpg',
      '/images/vehicles/command-03.jpg',
      '/images/vehicles/command-04.jpg',
    ],
    specs: {
      'Base Platform': 'Mercedes-Benz Sprinter 516 / Toyota Coaster',
      'Armour Type': 'Ballistic composite panels + laminated glass',
      'Protection Standard': 'EN 1063 BR6',
      'Engine': '3.0L Turbodiesel / 190 hp',
      'Transmission': 'Automatic',
      'Gross Vehicle Weight': '6,500 kg',
      'Command Capacity': 'Up to 8 operators',
      'Communications': 'Integrated multi-band radio',
      'Power': 'Shore power + 8kW generator',
      'Blast Protection': 'ERB Level 1',
    },
    highlights: ['Forward command capability', 'Multi-band comms', 'BR6 crew protection'],
    description:
      'The Mobile Command Vehicle converts a protected platform into a field headquarters. Configured with integrated communications systems, map tables, and independent power generation, it enables commanders to operate forward without dependence on fixed infrastructure.',
    optionalUpgrades: ['Satellite Uplink', 'Enhanced Comms Suite', 'Additional Generator', 'CCTV Monitor Stack'],
    weight: '6,500 kg',
    seats: 8,
  },
]

export function getAllVehicles(): Vehicle[] {
  return vehicles
}

export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug)
}

export function getVehiclesByCategory(category: 'civilian' | 'military'): Vehicle[] {
  return vehicles.filter((v) => v.category === category)
}

export function getRelatedVehicles(slug: string, count = 3): Vehicle[] {
  const vehicle = getVehicleBySlug(slug)
  if (!vehicle) return []
  return vehicles
    .filter((v) => v.slug !== slug && v.category === vehicle.category)
    .slice(0, count)
}
